# Generated by Django 5.0.1 on 2024-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('id_status', models.IntegerField()),
                ('current_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
