# Generated by Django 5.0.1 on 2024-05-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWO', '0002_alter_mymodel_message_alter_mymodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='message',
            field=models.TextField(default='Default message'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='status',
            field=models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('COMPLETED', 'Completed')], default='NEW', max_length=50),
        ),
    ]
